name: Continuous Integration

on:
  push:
    branches:
      - master
      - orleans-3.0
  pull_request:
    branches:
      - master
      - orleans-3.0

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build and Test
      run: |
        dotnet restore --verbosity minimal
        dotnet build --configuration Release --no-restore --verbosity minimal /p:TreatWarningsAsErrors=true /warnaserror
        dotnet test --configuration Release --no-build --no-restore --verbosity minimal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Include="[OrleansTestKit]*"
        dotnet pack --configuration Release --no-restore --verbosity minimal
    - name: Upload Packages
      uses: actions/upload-artifact@v1
      with:
        name: Packages
        path: artifacts/Release/
    # TODO: Need to create CODECOV_TOKEN secret.
    # - name: Upload Code Coverage Results
    #   env:
    #     CI: "true"
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    #   run: |
    #     bash <(curl -s https://codecov.io/bash) -f test/OrleansTestKit.Tests/coverage.opencover.xml
